apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: dfe4n055r-dotnet-basic
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-dotnet-basic:8250c5bc9dd2c0b3f0b9b8cd3979e848b9217ba0@sha256:361c7a33151dfc6e7201d2b3910101adf753aa72bac2fedbfd085000a7268ea0
          name: container-image
